name: Zip and Release WordPress Plugin

on:
  push:
    tags:
      - 'v*.*.*'  # This will trigger on any tag like v1.0.0, v1.2.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP file
      run: |
        mkdir output
        zip -r ../output/pco_plugin.zip . -x "*.git*" "*.github*" "tests/*"  # Exclude unnecessary files/folders

    - name: Create GitHub Release
      id: create_release
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"tag_name\": \"$VERSION\", \"name\": \"$VERSION\", \"body\": \"Release notes here...\"}" \
          https://api.github.com/repos/${{ github.repository }}/releases

    - name: Upload ZIP as release asset
      uses: softprops/action-gh-release@v1
      with:
        files: output/your-plugin.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
