name: Zip and Release WordPress Plugin

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP file
      run: |
        mkdir output
        zip -r output/pco_plugin.zip . -x "*.git*" "*.github*" "tests/*"

    - name: Create GitHub Release and Upload
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: "Automated release for version ${{ github.ref_name }}"
        files: output/pco_plugin.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}